SHELL := /bin/sh

PYTHON ?= python3
UV ?= uv
NPM ?= npm
ENV_FILE ?= .env
FOUNDRYCTL ?= $(if $(wildcard .tools/bin/foundryctl),.tools/bin/foundryctl,foundryctl)
SIGNOZ_COMPOSE := pours/deployment/compose.yaml

define with_env
	set -a; if [ -f "$(ENV_FILE)" ]; then . "$(ENV_FILE)"; fi; set +a; $(1)
endef

.DEFAULT_GOAL := help

.PHONY: help env install install-api install-web dev dev-api dev-web test test-api lint \
	typecheck build check reset seed unsafe-run investigate replay demo verify verify-signoz \
	signoz-forge signoz-lock signoz-up signoz-down signoz-status signoz-logs signoz-health \
	mcp-health signoz-key-check ollama-check signoz-provision signoz-dashboard signoz-alert

help: ## Show available commands.
	@awk 'BEGIN {FS = ":.*## "; print "RecallRoot commands:"} /^[a-zA-Z0-9_.-]+:.*## / {printf "  %-20s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

env: ## Create .env from the safe local template when it does not exist.
	@if [ -f "$(ENV_FILE)" ]; then echo "$(ENV_FILE) already exists"; else install -m 600 .env.example "$(ENV_FILE)"; echo "created $(ENV_FILE) with mode 600"; fi

install: install-api install-web ## Install locked API and web dependencies.

install-api: ## Install API dependencies, including development tools, with uv.
	$(UV) sync --project apps/api --extra dev --locked

install-web: ## Install web dependencies from package-lock.json.
	$(NPM) --prefix apps/web ci

dev: ## Run API (:8000) and web (:3000) with coordinated shutdown.
	@$(call with_env,$(PYTHON) scripts/dev.py)

dev-api: ## Run the FastAPI development server on :8000.
	@$(call with_env,$(UV) run --project apps/api uvicorn recallgraph.main:app --app-dir apps/api --reload --host "$${API_HOST:-127.0.0.1}" --port "$${API_PORT:-8000}")

dev-web: ## Run the Next.js development server on :3000.
	@$(call with_env,$(NPM) --prefix apps/web run dev -- --hostname "$${WEB_HOST:-127.0.0.1}" --port "$${WEB_PORT:-3000}")

test: test-api ## Run the automated test suite.

test-api: ## Run backend unit and integration tests.
	$(UV) run --project apps/api pytest -c apps/api/pyproject.toml apps/api/tests

lint: ## Lint Python and TypeScript sources.
	$(UV) run --project apps/api ruff check --config apps/api/pyproject.toml apps/api scripts
	$(UV) run --project apps/api ruff format --check --config apps/api/pyproject.toml apps/api scripts
	$(NPM) --prefix apps/web run lint

typecheck: ## Type-check the frontend.
	$(NPM) --prefix apps/web run typecheck

build: ## Build the production frontend bundle.
	$(NPM) --prefix apps/web run build

check: lint typecheck test build ## Run the same core checks as CI.
	$(PYTHON) -m compileall -q scripts
	$(PYTHON) -m json.tool infra/signoz/recallroot-dashboard.json >/dev/null
	$(PYTHON) -m json.tool infra/signoz/alert-rule.template.json >/dev/null

reset: ## Clear the deterministic demo's operational state.
	@$(call with_env,$(PYTHON) scripts/reset_demo.py)

seed: ## Seed the trusted policy and ingest Session A's unsafe memory.
	@$(call with_env,$(PYTHON) scripts/seed_demo.py)

unsafe-run: ## Run Session B and assert the silent policy violation.
	@$(call with_env,$(PYTHON) scripts/run_demo.py --unsafe-only)

investigate: ## Run the evidence-backed investigation for the latest incident.
	@$(call with_env,$(PYTHON) scripts/investigate_demo.py)

replay: ## Quarantine the causal memory and replay the original request.
	@$(call with_env,$(PYTHON) scripts/remediate_demo.py)

demo: ## Reset and execute the complete unsafe-run -> quarantine -> replay loop.
	@$(call with_env,$(PYTHON) scripts/run_demo.py)

verify: ## Verify API, causal graph, replay, and SigNoz when an API key is configured.
	@$(call with_env,$(PYTHON) scripts/verify_telemetry.py)

verify-signoz: ## Require current-run SigNoz/MCP evidence and alert firing history.
	@$(call with_env,$(PYTHON) scripts/verify_telemetry.py --require-signoz)

signoz-forge: ## Regenerate Foundry pours and the authentic casting lock.
	$(FOUNDRYCTL) forge -f casting.yaml --no-ledger --no-updater --format text

signoz-lock: signoz-forge ## Alias documenting the lock regeneration operation.
	@echo "casting.yaml.lock regenerated by $$($(FOUNDRYCTL) version 2>/dev/null | awk '/Version:/ {print $$2; exit}')"

signoz-up: ## Validate, forge, and start SigNoz through Foundry.
	$(FOUNDRYCTL) cast -f casting.yaml --no-ledger --no-updater --format text

signoz-down: ## Stop Foundry's generated Compose stack without deleting volumes.
	@test -f "$(SIGNOZ_COMPOSE)" || { echo "$(SIGNOZ_COMPOSE) is missing; run make signoz-forge first"; exit 1; }
	docker compose -f "$(SIGNOZ_COMPOSE)" down

signoz-status: ## Show Foundry-managed SigNoz container status.
	@test -f "$(SIGNOZ_COMPOSE)" || { echo "$(SIGNOZ_COMPOSE) is missing; run make signoz-forge first"; exit 1; }
	docker compose -f "$(SIGNOZ_COMPOSE)" ps

signoz-logs: ## Follow logs from the Foundry-managed SigNoz stack.
	@test -f "$(SIGNOZ_COMPOSE)" || { echo "$(SIGNOZ_COMPOSE) is missing; run make signoz-forge first"; exit 1; }
	docker compose -f "$(SIGNOZ_COMPOSE)" logs -f --tail=100

signoz-health: ## Check the SigNoz HTTP health endpoint on host port 3301.
	@$(call with_env,curl -fsS "$${SIGNOZ_URL:-http://localhost:3301}/api/v1/health")
	@echo

mcp-health: ## Check the Foundry-managed SigNoz MCP liveness endpoint on :8001.
	@curl -fsS http://localhost:8001/livez
	@echo

signoz-key-check: ## Validate the configured service-account key without printing it.
	@$(call with_env,$(PYTHON) scripts/check_signoz_key.py)

ollama-check: ## Verify the configured Ollama model against both controlled decisions.
	@$(call with_env,$(UV) run --project apps/api $(PYTHON) scripts/check_ollama.py)

signoz-provision: ## Create the dashboard and alert after validating the configured channel.
	@$(call with_env,$(PYTHON) scripts/provision_signoz.py)

signoz-dashboard: ## Create only the RecallRoot SigNoz dashboard.
	@$(call with_env,$(PYTHON) scripts/provision_signoz.py --dashboard-only)

signoz-alert: ## Create only the RecallRoot alert rule.
	@$(call with_env,$(PYTHON) scripts/provision_signoz.py --alert-only)
